const CONFIGURATION = {
    KEY_OPTIONS: [
        83, 70, 84, 69
    ],
    PARAMETERS: [{
        "easy_offer": 4.75,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 16
    }, {
        "easy_offer": 4.75,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 12
    }, {
        "easy_offer": 2,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 12
    }, {
        "easy_offer": 4.5,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 4
    }, {
        "easy_offer": 3,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 8
    }, {
        "easy_offer": 4,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 12
    }, {
        "easy_offer": 2,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 8
    }, {
        "easy_offer": 3,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 12
    }, {
        "easy_offer": 4.5,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 16
    }, {
        "easy_offer": 2,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 16
    }, {
        "easy_offer": 4,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 4
    }, {
        "easy_offer": 4.75,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 16
    }, {
        "easy_offer": 4.5,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 8
    }, {
        "easy_offer": 4.75,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 4
    }, {
        "easy_offer": 4,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 4
    }, {
        "easy_offer": 4.5,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 4
    }, {
        "easy_offer": 4,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 8
    }, {
        "easy_offer": 3,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 16
    }, {
        "easy_offer": 4,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 12
    }, {
        "easy_offer": 4.75,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 16
    }, {
        "easy_offer": 4.5,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 12
    }, {
        "easy_offer": 4.75,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 8
    }, {
        "easy_offer": 3,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 4
    }, {
        "easy_offer": 4.75,
        "easy_trials": 2,
        "hard_offer": 5,
        "hard_trials": 8
    }]
}